export interface Term {
  slug: string;
  label: string;
  short: string;     // <120 chars, used in tooltip
  long: string;      // longer definition, shown on glossary page
  also?: string[];   // alternate names / abbreviations
}

const list: Term[] = [
  { slug: "allowed-amount", label: "Allowed Amount", short: "The contracted price a payer recognizes for a service — the basis for splitting cost between plan and member.", long: "The dollar amount a payer agrees to pay (in total, across plan + member) for a covered service under a given contract. Typically the lesser of billed charge and contracted rate. The plan-paid and member-responsibility amounts are computed from the allowed amount, never from the billed charge." },
  { slug: "apc", label: "APC", short: "Ambulatory Payment Classification — the unit of payment in Medicare's outpatient prospective payment system (OPPS).", long: "Ambulatory Payment Classification. CMS groups outpatient procedures into APCs, each with a relative weight and dollar payment. Status indicators on each HCPCS code dictate whether it's separately payable, packaged into another service, or excluded from OPPS.", also: ["Ambulatory Payment Classification"] },
  { slug: "adjudication", label: "Adjudication", short: "The end-to-end process by which a payer evaluates a claim and decides what to pay.", long: "The full pipeline a payer runs on a received claim: eligibility check, coding edits, contract pricing, benefit application, COB, and payment determination. Output is an EOB to the member and an ERA/835 to the provider." },
  { slug: "asc", label: "ASC", short: "Ambulatory Surgery Center — a freestanding facility that performs same-day outpatient surgery.", long: "Ambulatory Surgery Center. Paid under a separate Medicare fee schedule (the ASC payment system), generally at lower rates than hospital outpatient (OPPS). Commercial contracts often peg ASCs to a percent of Medicare or to a custom fee schedule.", also: ["Ambulatory Surgery Center"] },
  { slug: "balance-billing", label: "Balance Billing", short: "When a provider bills the member for the difference between billed charge and allowed amount.", long: "Charging the patient for the gap between billed and allowed. In-network providers contractually cannot balance bill; out-of-network ones historically could. The federal No Surprises Act (2022) prohibits balance billing in many emergency and ancillary scenarios." },
  { slug: "billed-charge", label: "Billed Charge", short: "The provider's gross list price for a service, before any contract discounts.", long: "The gross amount the provider asks the payer to pay, drawn from the provider's chargemaster. Real prices in commercial healthcare are almost always far below billed charges; the billed amount is rarely what gets paid." },
  { slug: "bundled-payment", label: "Bundled Payment", short: "A single payment that covers an episode of care (multiple services or a span of time).", long: "An episode-based payment covering all services for a defined condition or procedure (e.g., joint replacement bundle covering surgery + 90 days post-op). Shifts care-coordination risk to the provider." },
  { slug: "carc", label: "CARC", short: "Claim Adjustment Reason Code — standard codes explaining why a payer reduced or denied a line.", long: "Claim Adjustment Reason Code. Standardized 1–3 digit codes (e.g., CO-45 'charge exceeds fee schedule', PR-1 'deductible amount') sent on the 835 ERA explaining each adjustment. Paired with RARCs for additional remark text.", also: ["Claim Adjustment Reason Code"] },
  { slug: "capitation", label: "Capitation", short: "A fixed per-member-per-month payment to a provider, regardless of utilization.", long: "A prospective monthly payment per attributed member (PMPM) that compensates the provider for managing some or all of that member's care. Shifts utilization risk to the provider. Common in primary care and Medicare Advantage." },
  { slug: "carve-out", label: "Carve-Out", short: "A service or item paid separately from a bundled rate, often at a different methodology.", long: "An exception to a bundled or per-diem contract under which specific high-cost items (implants, drugs, NICU stays, transplants) are paid separately — typically at percent of charges, invoice cost plus markup, or a separate fee schedule." },
  { slug: "case-rate", label: "Case Rate", short: "A flat payment per defined case (e.g., per delivery, per surgery), regardless of length of stay or services rendered.", long: "A single all-inclusive payment for a defined episode (e.g., $9,500 for a vaginal delivery covering all professional + facility services). Simpler than DRG but less granular." },
  { slug: "charge-master", label: "Charge Master", short: "A hospital's master list of gross prices for every billable item and service.", long: "Also called a 'chargemaster' or CDM. The hospital's internal price list, often containing 30,000+ line items at prices unrelated to actual reimbursement. Required to be public under federal price transparency rules but rarely useful to consumers because real payments come from contracts.", also: ["chargemaster", "CDM"] },
  { slug: "claim", label: "Claim", short: "The structured request a provider sends to a payer to be paid for services rendered.", long: "A formatted submission (paper CMS-1500/UB-04 or electronic 837P/837I) listing what was done, who did it, and what's being charged. Without a claim there's no payment." },
  { slug: "clearinghouse", label: "Clearinghouse", short: "An intermediary that scrubs and routes claims from providers to payers.", long: "A third party (e.g., Change Healthcare, Availity) that receives claims from providers, validates and reformats them, and forwards them to the appropriate payer. Reduces the N×M integration problem between providers and payers." },
  { slug: "cob", label: "COB", short: "Coordination of Benefits — rules for splitting payment when a member has more than one plan.", long: "Coordination of Benefits. The set of rules determining which plan pays first when a member has multiple coverages (e.g., spouse's plan + own plan, Medicare + commercial). Birthday rule, employee-vs-dependent rule, and others apply.", also: ["Coordination of Benefits"] },
  { slug: "coinsurance", label: "Coinsurance", short: "A percentage of the allowed amount the member pays after the deductible.", long: "Member's percentage share of the allowed amount, applied after deductible. Common rates: 20% in-network, 40–50% out-of-network. Distinct from copay (a flat dollar amount)." },
  { slug: "conversion-factor", label: "Conversion Factor", short: "The dollar multiplier in fee-schedule formulas (RBRVS, anesthesia) that converts RVUs to dollars.", long: "The dollar amount per RVU that converts relative units into payment. Medicare publishes a national CF annually (e.g., $32.74 in 2024). Anesthesia uses a separate conversion factor applied to base + time units." },
  { slug: "copay", label: "Copay", short: "A flat dollar amount the member pays at the time of service for a covered visit or service.", long: "Fixed dollar member responsibility (e.g., $30 for a primary care visit, $250 for an ER visit). Often applies regardless of where the deductible stands. Distinct from coinsurance, which is percentage-based." },
  { slug: "cpt", label: "CPT", short: "Current Procedural Terminology — the AMA's 5-digit codes for professional services and procedures.", long: "Current Procedural Terminology. Maintained by the AMA, used to identify the specific procedure or service rendered. Five-digit numeric codes (e.g., 99213 = established-patient office visit). Most professional reimbursement keys off CPT.", also: ["Current Procedural Terminology"] },
  { slug: "deductible", label: "Deductible", short: "The dollar amount the member must pay before the plan begins paying.", long: "Annual amount the member pays out-of-pocket before plan benefits kick in. Typical in-network values: $0 (rich plan) up to $7,000+ (HDHP). Resets each plan year. Some services (preventive care) bypass deductible entirely." },
  { slug: "drg", label: "DRG", short: "Diagnosis-Related Group — a bundled payment classification for inpatient stays.", long: "Diagnosis-Related Group. A classification system that groups inpatient stays by diagnosis, procedures, and severity into ~750 categories (MS-DRG variant for Medicare). Each DRG carries a weight; payment = base rate × weight × adjustments.", also: ["MS-DRG", "Diagnosis-Related Group"] },
  { slug: "edi-837", label: "EDI 837", short: "The electronic claim transaction (837P for professional, 837I for institutional).", long: "ANSI X12 standard for submitting healthcare claims electronically. 837P is the professional variant (replaces CMS-1500); 837I is the institutional variant (replaces UB-04); 837D covers dental." },
  { slug: "edi-835", label: "EDI 835", short: "The electronic remittance advice — the payer's reply to a claim, line by line.", long: "ANSI X12 standard for the electronic remittance advice (ERA). The payer's response to a claim: line-by-line allowed/paid/adjustments with CARC/RARC codes. The provider-side counterpart of the member's EOB." },
  { slug: "eob", label: "EOB", short: "Explanation of Benefits — a member-facing statement showing how a claim was processed.", long: "Explanation of Benefits. The statement a payer sends a member after processing a claim, showing billed, allowed, plan-paid, and member-responsibility amounts. 'This is not a bill' is the canonical disclaimer. The provider gets the equivalent info on an 835/ERA.", also: ["Explanation of Benefits"] },
  { slug: "era", label: "ERA", short: "Electronic Remittance Advice — the 835 transaction delivered to the provider.", long: "Electronic Remittance Advice. The provider-side artifact of adjudication, delivered as an EDI 835. Used to post payments and adjustments to the patient's account in the practice management system.", also: ["Electronic Remittance Advice"] },
  { slug: "fee-schedule", label: "Fee Schedule", short: "A list of allowed amounts indexed by procedure code.", long: "A table mapping each CPT/HCPCS code (and sometimes modifier) to an allowed amount. The basic primitive of professional and outpatient pricing. Medicare's MPFS is the most widely referenced; commercial schedules often expressed as a percent of Medicare." },
  { slug: "fqhc", label: "FQHC", short: "Federally Qualified Health Center — paid under a special encounter-based methodology.", long: "Federally Qualified Health Center. Community-based clinic paid under a Medicare PPS encounter rate (one rate per face-to-face visit, regardless of services rendered) instead of fee-for-service. Similar models exist for RHCs and CAHs.", also: ["Federally Qualified Health Center"] },
  { slug: "gpci", label: "GPCI", short: "Geographic Practice Cost Index — locality adjuster in the RBRVS formula.", long: "Geographic Practice Cost Index. CMS publishes three GPCIs per Medicare locality (work, practice expense, malpractice) that adjust the corresponding RVUs. Effectively a regional cost-of-living index for the RBRVS formula.", also: ["Geographic Practice Cost Index"] },
  { slug: "hcpcs", label: "HCPCS", short: "Healthcare Common Procedure Coding System — superset of CPT plus J-codes (drugs), DME, etc.", long: "HCPCS = HCPCS Level I (= CPT) + HCPCS Level II (alphanumeric codes for drugs, DME, ambulance, supplies, etc.). When a procedure has no CPT, it's typically coded with a Level II HCPCS.", also: ["Healthcare Common Procedure Coding System"] },
  { slug: "icd-10", label: "ICD-10", short: "International Classification of Diseases, 10th revision — diagnosis codes.", long: "ICD-10-CM in the US. Diagnosis codes that justify the medical necessity of services billed via CPT/HCPCS. Primary diagnosis often drives DRG assignment for inpatient stays. ICD-11 adoption is happening slowly.", also: ["ICD-10-CM"] },
  { slug: "ime-dsh", label: "IME / DSH", short: "Indirect Medical Education / Disproportionate Share — DRG add-ons for teaching hospitals and safety-net providers.", long: "Two add-on payments to the base DRG: IME (Indirect Medical Education) compensates teaching hospitals for higher costs of training residents; DSH (Disproportionate Share Hospital) supplements hospitals serving a high proportion of Medicaid/uninsured patients.", also: ["IME", "DSH"] },
  { slug: "lesser-of", label: "Lesser-Of", short: "Contractual logic that pays the minimum of billed charge and contracted rate.", long: "A near-universal contract clause: the allowed amount is the lesser of (a) the provider's billed charge and (b) the contracted rate. Prevents a provider from collecting more than they billed even if the contracted rate is higher." },
  { slug: "ma-plan", label: "MA Plan", short: "Medicare Advantage — a private plan that replaces Original Medicare for an enrolled member.", long: "Medicare Advantage (Part C). Private health plans that contract with CMS to deliver Medicare benefits. Paid by CMS via risk-adjusted PMPM capitation; in turn, MA plans negotiate their own provider contracts (often pegged to % of Medicare).", also: ["Medicare Advantage"] },
  { slug: "mlr", label: "MLR", short: "Medical Loss Ratio — the share of premium spent on claims and quality.", long: "Medical Loss Ratio. ACA-mandated minimum: 80% (individual/small group) or 85% (large group) of premium must be spent on claims + quality improvement, or rebates are owed. Drives a lot of payer behavior around contracting and admin spend.", also: ["Medical Loss Ratio"] },
  { slug: "modifier", label: "Modifier", short: "A 2-character suffix on a CPT/HCPCS code that alters its meaning or pricing.", long: "Two-character suffix appended to a CPT/HCPCS code that signals a variation: -25 (significant separately identifiable E&M same day), -59 (distinct service), -50 (bilateral), -51 (multiple procedure), -26 (professional component), -TC (technical component). Modifiers can change pricing materially." },
  { slug: "mue", label: "MUE", short: "Medically Unlikely Edit — a CMS cap on units of a code billable per day per patient.", long: "Medically Unlikely Edit. A maximum number of units of a given HCPCS/CPT code that CMS will pay per patient per day. Designed to catch billing errors (e.g., 20 units of a procedure that's only done once).", also: ["Medically Unlikely Edit"] },
  { slug: "ncci", label: "NCCI", short: "National Correct Coding Initiative — CMS edits that prevent unbundling and incompatible code pairs.", long: "National Correct Coding Initiative. CMS-published edit pairs (PTP edits) that flag combinations of codes that shouldn't be billed together — e.g., a comprehensive code already includes a component code. Most payers apply NCCI logic during adjudication.", also: ["National Correct Coding Initiative"] },
  { slug: "ndc", label: "NDC", short: "National Drug Code — 11-digit identifier for a specific drug/strength/package.", long: "National Drug Code. Identifies a specific manufactured drug down to formulation, strength, and package size. Used on claims for drugs administered in office (J-code + NDC) and for pharmacy claims.", also: ["National Drug Code"] },
  { slug: "nsa", label: "NSA", short: "No Surprises Act — federal law (2022) banning surprise balance billing in many situations.", long: "No Surprises Act. Effective Jan 1, 2022. Prohibits balance billing for emergency services, air ambulance, and out-of-network providers at in-network facilities. Establishes an Independent Dispute Resolution (IDR) process for payer-provider rate disputes in scoped scenarios.", also: ["No Surprises Act"] },
  { slug: "oop-max", label: "OOP Max", short: "Out-of-pocket maximum — the cap on what a member pays in a plan year.", long: "Out-of-Pocket Maximum. Annual ceiling on member cost-sharing (deductible + copays + coinsurance). Once hit, the plan pays 100% of allowed amount for the rest of the year. ACA caps this at federally set values, but only for in-network essential health benefits.", also: ["Out-of-Pocket Maximum"] },
  { slug: "opps", label: "OPPS", short: "Outpatient Prospective Payment System — Medicare's APC-based payment for hospital outpatient services.", long: "Outpatient Prospective Payment System. The Medicare methodology for hospital outpatient claims, built on APCs with status-indicator-driven packaging logic. Many commercial contracts borrow this structure.", also: ["Outpatient Prospective Payment System"] },
  { slug: "outlier", label: "Outlier", short: "A high-cost case that earns an extra payment beyond the standard DRG/APC amount.", long: "When a stay's actual cost (estimated as charges × cost-to-charge ratio) exceeds a threshold, payers add an outlier payment to compensate. Medicare uses a fixed-loss threshold; commercial contracts often define their own stop-loss at a charge or cost trigger." },
  { slug: "par-provider", label: "Par Provider", short: "Participating provider — has a contract with the payer; in-network.", long: "Short for 'participating provider'. A provider who has signed a contract with the payer agreeing to accept the payer's allowed amounts as payment in full. Contrast with non-par (no contract) — out-of-network." },
  { slug: "payer", label: "Payer", short: "The entity financially responsible for paying the claim — insurer, MA plan, employer plan, Medicaid MCO, etc.", long: "The party that bears financial responsibility for healthcare claims. Examples: commercial insurers (UnitedHealthcare, Anthem), self-insured employer plans (administered by a TPA), Medicare Advantage organizations, Medicaid Managed Care Organizations, Original Medicare itself." },
  { slug: "per-diem", label: "Per Diem", short: "A flat daily rate for inpatient stay, often tiered by level of care.", long: "Daily rate for inpatient services, often varying by level of care (med-surg vs ICU vs NICU). Common in commercial hospital contracts. Rate covers all services that day except contracted carve-outs (implants, drugs, etc.)." },
  { slug: "percent-of-charges", label: "Percent of Charges", short: "Pricing methodology: payment = some percentage of billed charges.", long: "A reimbursement method in which the allowed amount is computed as a percentage of the provider's billed charges (e.g., 65% of charges). Loss of cost discipline for the payer because the provider sets its own charges, but common as a fallback for services without other rates." },
  { slug: "pmpm", label: "PMPM", short: "Per Member Per Month — the unit of capitated payment.", long: "Per Member Per Month. The unit in which capitated payments are quoted: e.g., a primary care cap of $25 PMPM for an attributed panel. Multiply by panel size to get the monthly payment." },
  { slug: "pos", label: "POS", short: "Place of Service — 2-digit code identifying where the service occurred (office, hospital, ER, telehealth, etc.).", long: "Place of Service. Two-digit code on the claim identifying the setting (11 = office, 21 = inpatient hospital, 22 = on-campus outpatient, 23 = ER, 02 = telehealth). POS often drives whether the facility/non-facility variant of the fee schedule applies.", also: ["Place of Service"] },
  { slug: "rarc", label: "RARC", short: "Remittance Advice Remark Code — supplementary explanation accompanying CARCs on the 835.", long: "Remittance Advice Remark Code. Additional explanatory text codes (e.g., M127 'Missing patient medical record') that accompany CARCs on the 835 to explain non-financial reasons or provide more detail.", also: ["Remittance Advice Remark Code"] },
  { slug: "rbrvs", label: "RBRVS", short: "Resource-Based Relative Value Scale — the formula behind the Medicare physician fee schedule.", long: "Resource-Based Relative Value Scale. The framework underlying the Medicare Physician Fee Schedule (MPFS). Each CPT has work, practice expense, and malpractice RVUs; each is GPCI-adjusted; the sum × the conversion factor = allowed amount.", also: ["Resource-Based Relative Value Scale", "MPFS"] },
  { slug: "reference-based-pricing", label: "Reference-Based Pricing", short: "Pricing strategy that benchmarks allowed amounts to a public reference (typically Medicare).", long: "A payer (often a self-insured employer) sets allowed amounts at a fixed multiple of Medicare (e.g., 140% of Medicare) instead of negotiating contracts with each provider. Cuts admin cost but risks balance billing because providers haven't agreed to the rate." },
  { slug: "revenue-code", label: "Revenue Code", short: "4-digit UB-04 code identifying the type of service or department for institutional claims.", long: "Four-digit code on UB-04/837I claims identifying the cost center or service type (e.g., 0250 = pharmacy, 0450 = ER, 0636 = drugs requiring detailed coding). Hospital pricing often keys off revenue code rather than (or in addition to) HCPCS." },
  { slug: "rvu", label: "RVU", short: "Relative Value Unit — the input to the RBRVS formula.", long: "Relative Value Unit. Three flavors per CPT: work RVU (physician time/effort), practice expense RVU (facility or non-facility), and malpractice RVU. CMS publishes them annually. Multiply each by its GPCI, sum, multiply by conversion factor → Medicare allowed amount.", also: ["Relative Value Unit"] },
  { slug: "stop-loss", label: "Stop-Loss", short: "A threshold above which payment switches to a different (usually higher) methodology.", long: "Two meanings: (1) in hospital contracts, a charge threshold (e.g., $250k) above which payment flips from per diem to percent of charges; (2) in self-insured employer plans, reinsurance against catastrophic claims. Both protect against extreme cases — for the provider in (1), for the employer in (2)." },
  { slug: "subrogation", label: "Subrogation", short: "Recovering payment from a third party legally responsible for the medical event (e.g., auto insurer).", long: "When a member's injury was caused by a third party (car accident, slip-and-fall), the health plan can pay the claims and then recover from the at-fault party's liability insurer. Health plan adjudicates first, recovers second." },
  { slug: "type-of-bill", label: "Type of Bill", short: "3-digit code on UB-04 indicating facility type, bill classification, and claim frequency.", long: "Three-digit code on UB-04/837I claims: position 1 = facility type (e.g., 1 hospital, 2 SNF), position 2 = bill classification (1 inpatient, 3 outpatient), position 3 = frequency (1 admit-thru-discharge, 7 replacement). E.g., 111 = inpatient hospital admit-thru-discharge claim.", also: ["TOB"] },
  { slug: "ub-04", label: "UB-04", short: "The institutional paper claim form (also called CMS-1450); electronic equivalent is 837I.", long: "Universal Billing form (revision 2004). The standard paper claim used by hospitals, nursing facilities, hospices, and other institutional providers. Electronic equivalent: EDI 837I. Carries revenue codes, type of bill, occurrence/value codes, condition codes, and HCPCS where applicable.", also: ["CMS-1450"] },
  { slug: "ucr", label: "Usual & Customary", short: "A benchmark of typical charges in a geographic area, historically used for out-of-network pricing.", long: "Usual, Customary & Reasonable. Historically the basis for out-of-network allowed amounts: payers paid up to a percentile (e.g., 80th) of charges in the area. Largely supplanted by reference-based pricing tied to Medicare, but the term still appears in older contracts and benefit booklets.", also: ["UCR", "Usual, Customary & Reasonable"] },
  { slug: "wage-index", label: "Wage Index", short: "CMS-published locality factor that adjusts the labor portion of the DRG base rate.", long: "Annual CMS index reflecting hospital wages in a Core-Based Statistical Area (CBSA) relative to the national average. Applied to the labor share (~67.7%) of the DRG base rate, leaving the non-labor share unadjusted." },
  { slug: "write-off", label: "Write-Off", short: "The portion of billed charge above the allowed amount that the provider must absorb.", long: "Contractual adjustment: billed charge minus allowed amount. The provider cannot collect this from the member (when in-network) and writes it off as a non-collectible adjustment. Often the largest line on a hospital's revenue reconciliation." },
  { slug: "cms-1500", label: "CMS-1500", short: "The professional paper claim form; electronic equivalent is 837P.", long: "Standard paper claim used by physicians, professional groups, ASCs in some cases, and other non-institutional providers. Electronic equivalent: EDI 837P. Carries CPT/HCPCS codes, modifiers, ICD-10 diagnoses, and place of service.", also: ["837P"] },
  { slug: "global-period", label: "Global Period", short: "Days surrounding a surgery during which related E&M services are bundled into the surgical fee.", long: "Days before and after a procedure during which related evaluation/management services are not separately payable — typically 0, 10, or 90 days for major surgery in Medicare. Modifier -24 unbundles unrelated E&M; modifier -79 unbundles unrelated procedures." },
  { slug: "anesthesia-cf", label: "Anesthesia CF", short: "Conversion factor specific to anesthesia services; multiplied by (base units + time units).", long: "Anesthesia uses a separate fee-schedule formula: payment = (base units + time units) × anesthesia conversion factor. Base units come from the ASA code; time units are typically 15-minute increments. Modifiers QK/QY/QX adjust for medical-direction scenarios." },
  { slug: "accumulator", label: "Accumulator", short: "Running totals on a member's plan tracking deductible spent, OOP spent, etc.", long: "Per-member, per-plan-year counters: deductible-met, OOP-met, lifetime max (less common now post-ACA). Updated as claims adjudicate. Many plans separate individual vs family accumulators with embedded vs non-embedded rules." },
  { slug: "embedded-deductible", label: "Embedded Deductible", short: "Each individual on a family plan has their own deductible, capped by the family deductible.", long: "An individual deductible 'embedded' inside a family deductible: any single member can hit the individual deductible without the whole family meeting the family deductible. Compare to non-embedded ('aggregate'), where the entire family deductible must be met before any benefits apply." },
];

const map: Map<string, Term> = new Map(list.map((t) => [t.slug, t]));

export function getTerm(slug: string): Term | undefined {
  return map.get(slug);
}

export function allTerms(): Term[] {
  return list.slice().sort((a, b) => a.label.localeCompare(b.label));
}
